pool:
  res_origin_list:
    - https://0.webui-test.museai.cc
    - https://1.webui-test.museai.cc
#    - https://2.webui.museai.cc
  dl_server_origin: https://dl.webui-test.museai.cc
  max_running_timeout: 600